name: Flutter Self-Hosted Check

on:
  workflow_dispatch:

jobs:
  flutter-check:
    name: Flutter check on my Windows PC
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Flutter version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Build debug APK
        run: flutter build apk --debug
